import { PDFDocument, PDFPage, PDFFont, StandardFonts, rgb } from "pdf-lib";
import type { ComplianceData } from "./types";

const NAVY = rgb(30 / 255, 58 / 255, 95 / 255);
const LIGHT_ROW = rgb(248 / 255, 249 / 255, 250 / 255);
const WHITE_RGB = rgb(1, 1, 1);
const TEXT_RGB = rgb(0.2, 0.2, 0.2);
const MUTED_RGB = rgb(0.4, 0.4, 0.4);
const MARGIN = 50;
const PAGE_W = 612;
const PAGE_H = 792;
const CONTENT_W = PAGE_W - MARGIN * 2;

interface Fonts {
  regular: PDFFont;
  bold: PDFFont;
}

interface Cursor {
  page: PDFPage;
  y: number;
}

export async function generateCompliancePDF(data: ComplianceData): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const fonts: Fonts = { regular, bold };

  const pages: Cursor[] = [];
  function newPage(): Cursor {
    const page = doc.addPage([PAGE_W, PAGE_H]);
    const c: Cursor = { page, y: PAGE_H - MARGIN };
    pages.push(c);
    return c;
  }

  drawCoverPage(newPage(), fonts, data);
  drawTableOfContents(newPage(), fonts);
  drawExecutiveSummary(newPage(), fonts, data);
  drawAgentInventory(newPage(), fonts, data, doc);
  drawPaymentActivity(newPage(), fonts, data, doc);
  drawBudgetCompliance(newPage(), fonts, data, doc);
  drawReceiptLog(newPage(), fonts, data, doc);
  drawAlertSummary(newPage(), fonts, data, doc);
  drawRiskAssessment(newPage(), fonts, data);

  addFooters(doc, fonts);

  const pdfBytes = await doc.save();
  return Buffer.from(pdfBytes);
}

// --- Sections ---

function drawCoverPage(cur: Cursor, fonts: Fonts, data: ComplianceData) {
  const { page } = cur;

  page.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: PAGE_H, color: NAVY });

  page.drawText("x402 Payment", { x: MARGIN, y: 580, size: 32, font: fonts.bold, color: WHITE_RGB });
  page.drawText("Compliance Report", { x: MARGIN, y: 540, size: 32, font: fonts.bold, color: WHITE_RGB });

  const subtitleColor = rgb(170 / 255, 187 / 255, 204 / 255);
  page.drawText(data.teamName, { x: MARGIN, y: 475, size: 14, font: fonts.regular, color: subtitleColor });
  page.drawText(`${formatDate(data.startDate)} — ${formatDate(data.endDate)}`, {
    x: MARGIN, y: 450, size: 12, font: fonts.regular, color: subtitleColor,
  });
  page.drawText(`Generated: ${formatDateTime(data.generatedAt)}`, {
    x: MARGIN, y: 425, size: 10, font: fonts.regular, color: subtitleColor,
  });

  const footerColor = rgb(136 / 255, 153 / 255, 170 / 255);
  const footerText = "Generated by Sentinel | sentinel.valeocash.com";
  const footerW = fonts.regular.widthOfTextAtSize(footerText, 10);
  page.drawText(footerText, {
    x: (PAGE_W - footerW) / 2, y: 60, size: 10, font: fonts.regular, color: footerColor,
  });
}

function drawTableOfContents(cur: Cursor, fonts: Fonts) {
  sectionTitle(cur, fonts, "Table of Contents");

  const sections = [
    "1. Executive Summary",
    "2. Agent Inventory",
    "3. Payment Activity",
    "4. Budget Compliance",
    "5. Receipt Verification Log",
    "6. Alert Summary",
    "7. Risk Assessment",
  ];

  for (const s of sections) {
    cur.y -= 4;
    cur.page.drawText(s, { x: MARGIN + 20, y: cur.y, size: 11, font: fonts.regular, color: TEXT_RGB });
    cur.y -= 20;
  }
}

function drawExecutiveSummary(cur: Cursor, fonts: Fonts, data: ComplianceData) {
  sectionTitle(cur, fonts, "1. Executive Summary");

  const s = data.summary;
  const stats = [
    ["Total Payments", s.total_payments.toLocaleString()],
    ["Total Spend", `$${s.total_spent_usd.toFixed(2)}`],
    ["Active Agents", s.active_agents.toString()],
    ["Unique Endpoints", s.unique_endpoints.toString()],
    ["Avg Payment", `$${s.avg_payment_usd.toFixed(4)}`],
    ["Max Payment", `$${s.max_payment_usd.toFixed(4)}`],
    ["Failed Payments", s.total_failed.toString()],
    ["Blocked Payments", s.total_blocked.toString()],
  ];

  const colW = CONTENT_W / 2;
  for (let i = 0; i < stats.length; i += 2) {
    const left = stats[i]!;
    const right = stats[i + 1];

    cur.page.drawText(left[0]!, { x: MARGIN, y: cur.y, size: 9, font: fonts.regular, color: MUTED_RGB });
    cur.page.drawText(left[1]!, { x: MARGIN, y: cur.y - 14, size: 13, font: fonts.bold, color: TEXT_RGB });

    if (right) {
      cur.page.drawText(right[0]!, { x: MARGIN + colW, y: cur.y, size: 9, font: fonts.regular, color: MUTED_RGB });
      cur.page.drawText(right[1]!, { x: MARGIN + colW, y: cur.y - 14, size: 13, font: fonts.bold, color: TEXT_RGB });
    }

    cur.y -= 40;
  }
}

function drawAgentInventory(cur: Cursor, fonts: Fonts, data: ComplianceData, doc: PDFDocument) {
  sectionTitle(cur, fonts, "2. Agent Inventory");

  if (data.byAgent.length === 0) {
    cur.page.drawText("No agent activity in the selected period.", { x: MARGIN, y: cur.y, size: 10, font: fonts.regular, color: MUTED_RGB });
    return;
  }

  const cols = [
    { header: "Agent ID", width: 140 },
    { header: "Payments", width: 70 },
    { header: "Total Spend", width: 90 },
    { header: "Avg / Payment", width: 90 },
  ];

  const rows = data.byAgent.map((a) => [
    a.agent_id,
    a.count.toString(),
    `$${a.total_usd.toFixed(2)}`,
    `$${(a.count > 0 ? a.total_usd / a.count : 0).toFixed(4)}`,
  ]);

  drawTable(cur, fonts, cols, rows, doc);
}

function drawPaymentActivity(cur: Cursor, fonts: Fonts, data: ComplianceData, doc: PDFDocument) {
  sectionTitle(cur, fonts, "3. Payment Activity");

  if (data.payments.length === 0) {
    cur.page.drawText("No payments in the selected period.", { x: MARGIN, y: cur.y, size: 10, font: fonts.regular, color: MUTED_RGB });
    return;
  }

  const cols = [
    { header: "Date", width: 75 },
    { header: "Agent", width: 80 },
    { header: "Endpoint", width: 100 },
    { header: "Amount", width: 70 },
    { header: "Network", width: 55 },
    { header: "Status", width: 50 },
  ];

  const rows = data.payments.slice(0, 200).map((p) => [
    formatDate(p.timestamp),
    truncate(p.agentExternalId, 12),
    truncate(p.endpoint, 16),
    p.amountUsd != null ? `$${p.amountUsd.toFixed(4)}` : p.amount ?? "—",
    p.network ?? "—",
    p.status,
  ]);

  drawTable(cur, fonts, cols, rows, doc);

  if (data.payments.length > 200) {
    cur.y -= 6;
    cur.page.drawText(
      `Showing 200 of ${data.payments.length} payments. Full data available in the dashboard.`,
      { x: MARGIN, y: cur.y, size: 9, font: fonts.regular, color: MUTED_RGB }
    );
    cur.y -= 14;
  }
}

function drawBudgetCompliance(cur: Cursor, fonts: Fonts, data: ComplianceData, doc: PDFDocument) {
  sectionTitle(cur, fonts, "4. Budget Compliance");

  const activePolicies = data.policies.filter((p) => p.isActive);
  const totalPayments = data.summary.total_payments;
  const blocked = data.summary.total_blocked;
  const complianceRate = totalPayments > 0 ? ((totalPayments - blocked) / totalPayments) * 100 : 100;

  const lines = [
    `Active Policies: ${activePolicies.length}`,
    `Blocked Payments: ${blocked}`,
    `Compliance Rate: ${complianceRate.toFixed(1)}%`,
  ];

  for (const line of lines) {
    cur.page.drawText(line, { x: MARGIN, y: cur.y, size: 11, font: fonts.regular, color: TEXT_RGB });
    cur.y -= 18;
  }
  cur.y -= 8;

  if (activePolicies.length > 0) {
    const cols = [
      { header: "Policy Name", width: 180 },
      { header: "Agent", width: 120 },
      { header: "Active", width: 60 },
    ];

    const rows = activePolicies.map((p) => [
      p.name,
      p.agentExternalId ?? "All agents",
      p.isActive ? "Yes" : "No",
    ]);

    drawTable(cur, fonts, cols, rows, doc);
  } else {
    cur.page.drawText("No budget policies configured.", { x: MARGIN, y: cur.y, size: 10, font: fonts.regular, color: MUTED_RGB });
  }
}

function drawReceiptLog(cur: Cursor, fonts: Fonts, data: ComplianceData, doc: PDFDocument) {
  sectionTitle(cur, fonts, "5. Receipt Verification Log");

  const total = data.receipts.length;
  const verified = data.receipts.filter((r) => r.verified).length;
  const verifyRate = total > 0 ? ((verified / total) * 100).toFixed(1) : "N/A";

  const lines = [
    `Total Receipts: ${total}`,
    `Verified: ${verified}`,
    `Verification Rate: ${verifyRate}%`,
  ];

  for (const line of lines) {
    cur.page.drawText(line, { x: MARGIN, y: cur.y, size: 11, font: fonts.regular, color: TEXT_RGB });
    cur.y -= 18;
  }
  cur.y -= 8;

  if (data.receipts.length > 0) {
    const cols = [
      { header: "Receipt ID", width: 150 },
      { header: "Payment ID", width: 150 },
      { header: "Verified", width: 60 },
      { header: "Created", width: 90 },
    ];

    const rows = data.receipts.slice(0, 100).map((r) => [
      truncate(r.id, 20),
      truncate(r.paymentId ?? "—", 20),
      r.verified ? "Yes" : "No",
      formatDate(r.createdAt.toISOString()),
    ]);

    drawTable(cur, fonts, cols, rows, doc);
  }
}

function drawAlertSummary(cur: Cursor, fonts: Fonts, data: ComplianceData, doc: PDFDocument) {
  sectionTitle(cur, fonts, "6. Alert Summary");

  if (data.alerts.length === 0) {
    cur.page.drawText("No alerts triggered in the selected period.", { x: MARGIN, y: cur.y, size: 10, font: fonts.regular, color: MUTED_RGB });
    return;
  }

  const cols = [
    { header: "Date", width: 80 },
    { header: "Type", width: 80 },
    { header: "Severity", width: 65 },
    { header: "Message", width: 190 },
    { header: "Resolved", width: 55 },
  ];

  const rows = data.alerts.slice(0, 100).map((a) => [
    formatDate(a.createdAt.toISOString()),
    a.type,
    a.severity,
    truncate(a.message, 35),
    a.resolved ? "Yes" : "No",
  ]);

  drawTable(cur, fonts, cols, rows, doc);
}

function drawRiskAssessment(cur: Cursor, fonts: Fonts, data: ComplianceData) {
  sectionTitle(cur, fonts, "7. Risk Assessment");

  const { risk } = data;
  const levelColor = risk.level === "Low" ? rgb(34 / 255, 197 / 255, 94 / 255)
    : risk.level === "Medium" ? rgb(234 / 255, 179 / 255, 8 / 255)
    : rgb(239 / 255, 68 / 255, 68 / 255);

  cur.page.drawText(`Risk Level: ${risk.level}`, { x: MARGIN, y: cur.y, size: 14, font: fonts.bold, color: levelColor });
  cur.y -= 28;

  cur.page.drawText("Findings:", { x: MARGIN, y: cur.y, size: 11, font: fonts.bold, color: TEXT_RGB });
  cur.y -= 18;

  for (const f of risk.findings) {
    cur.page.drawText(`•  ${f}`, { x: MARGIN + 10, y: cur.y, size: 10, font: fonts.regular, color: TEXT_RGB });
    cur.y -= 16;
  }

  if (risk.recommendations.length > 0) {
    cur.y -= 10;
    cur.page.drawText("Recommendations:", { x: MARGIN, y: cur.y, size: 11, font: fonts.bold, color: TEXT_RGB });
    cur.y -= 18;

    for (const r of risk.recommendations) {
      cur.page.drawText(`•  ${r}`, { x: MARGIN + 10, y: cur.y, size: 10, font: fonts.regular, color: TEXT_RGB });
      cur.y -= 16;
    }
  }
}

// --- Helpers ---

function sectionTitle(cur: Cursor, fonts: Fonts, title: string) {
  cur.page.drawText(title, { x: MARGIN, y: cur.y, size: 16, font: fonts.bold, color: NAVY });
  cur.y -= 6;
  cur.page.drawLine({
    start: { x: MARGIN, y: cur.y },
    end: { x: MARGIN + CONTENT_W, y: cur.y },
    thickness: 1,
    color: NAVY,
  });
  cur.y -= 20;
}

interface Column {
  header: string;
  width: number;
}

function drawTable(cur: Cursor, fonts: Fonts, columns: Column[], rows: string[][], doc: PDFDocument) {
  const ROW_H = 18;

  function drawHeader() {
    cur.page.drawRectangle({ x: MARGIN, y: cur.y - ROW_H, width: CONTENT_W, height: ROW_H, color: NAVY });
    let x = MARGIN;
    for (const col of columns) {
      const text = clipText(col.header, col.width - 8, 8, fonts.bold);
      cur.page.drawText(text, { x: x + 4, y: cur.y - 13, size: 8, font: fonts.bold, color: WHITE_RGB });
      x += col.width;
    }
    cur.y -= ROW_H;
  }

  drawHeader();

  for (let i = 0; i < rows.length; i++) {
    if (cur.y - ROW_H < MARGIN + 20) {
      const newPage = doc.addPage([PAGE_W, PAGE_H]);
      cur.page = newPage;
      cur.y = PAGE_H - MARGIN;
      drawHeader();
    }

    const bgColor = i % 2 === 0 ? WHITE_RGB : LIGHT_ROW;
    cur.page.drawRectangle({ x: MARGIN, y: cur.y - ROW_H, width: CONTENT_W, height: ROW_H, color: bgColor });

    let x = MARGIN;
    const row = rows[i]!;
    for (let j = 0; j < columns.length; j++) {
      const cellText = clipText(row[j] ?? "", columns[j]!.width - 8, 8, fonts.regular);
      cur.page.drawText(cellText, { x: x + 4, y: cur.y - 13, size: 8, font: fonts.regular, color: TEXT_RGB });
      x += columns[j]!.width;
    }
    cur.y -= ROW_H;
  }

  cur.y -= 4;
}

function addFooters(doc: PDFDocument, fonts: Fonts) {
  const pages = doc.getPages();
  const totalContent = pages.length - 1; // exclude cover
  for (let i = 1; i < pages.length; i++) {
    const page = pages[i]!;
    const text = `Generated by Sentinel  |  sentinel.valeocash.com  |  Page ${i} of ${totalContent}`;
    const textW = fonts.regular.widthOfTextAtSize(text, 7);
    page.drawText(text, {
      x: (PAGE_W - textW) / 2,
      y: 20,
      size: 7,
      font: fonts.regular,
      color: MUTED_RGB,
    });
  }
}

function clipText(text: string, maxWidth: number, fontSize: number, font: PDFFont): string {
  if (font.widthOfTextAtSize(text, fontSize) <= maxWidth) return text;
  let clipped = text;
  while (clipped.length > 1 && font.widthOfTextAtSize(clipped + "…", fontSize) > maxWidth) {
    clipped = clipped.slice(0, -1);
  }
  return clipped + "…";
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function formatDateTime(iso: string): string {
  const d = new Date(iso);
  return `${formatDate(iso)} ${d.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "UTC" })} UTC`;
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max - 3) + "..." : s;
}
