import PDFDocument from "pdfkit";
import type { ComplianceData } from "./types";

const NAVY = "#1e3a5f";
const LIGHT_ROW = "#f8f9fa";
const WHITE = "#ffffff";
const TEXT_COLOR = "#333333";
const MUTED = "#666666";
const MARGIN = 50;
const PAGE_WIDTH = 612;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

export async function generateCompliancePDF(data: ComplianceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: MARGIN, bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    drawCoverPage(doc, data);
    drawTableOfContents(doc);
    drawExecutiveSummary(doc, data);
    drawAgentInventory(doc, data);
    drawPaymentActivity(doc, data);
    drawBudgetCompliance(doc, data);
    drawReceiptLog(doc, data);
    drawAlertSummary(doc, data);
    drawRiskAssessment(doc, data);

    addFooters(doc);

    doc.end();
  });
}

function drawCoverPage(doc: PDFKit.PDFDocument, data: ComplianceData) {
  doc.rect(0, 0, PAGE_WIDTH, 792).fill(NAVY);

  doc.fontSize(32).fill(WHITE).text("x402 Payment", MARGIN, 200, { width: CONTENT_WIDTH });
  doc.fontSize(32).fill(WHITE).text("Compliance Report", MARGIN, 240, { width: CONTENT_WIDTH });

  doc.moveDown(2);
  doc.fontSize(14).fill("#aabbcc").text(data.teamName, MARGIN, 310, { width: CONTENT_WIDTH });
  doc.fontSize(12).text(
    `${formatDate(data.startDate)} — ${formatDate(data.endDate)}`,
    MARGIN,
    335,
    { width: CONTENT_WIDTH }
  );
  doc.fontSize(10).text(
    `Generated: ${formatDateTime(data.generatedAt)}`,
    MARGIN,
    365,
    { width: CONTENT_WIDTH }
  );

  doc.fontSize(10).fill("#8899aa").text(
    "Generated by Sentinel | sentinel.valeocash.com",
    MARGIN,
    700,
    { width: CONTENT_WIDTH, align: "center" }
  );
}

function drawTableOfContents(doc: PDFKit.PDFDocument) {
  doc.addPage();
  sectionTitle(doc, "Table of Contents");
  doc.fontSize(11).fill(TEXT_COLOR);

  const sections = [
    "1. Executive Summary",
    "2. Agent Inventory",
    "3. Payment Activity",
    "4. Budget Compliance",
    "5. Receipt Verification Log",
    "6. Alert Summary",
    "7. Risk Assessment",
  ];

  let y = doc.y + 10;
  for (const s of sections) {
    doc.text(s, MARGIN + 20, y, { width: CONTENT_WIDTH });
    y += 24;
  }
}

function drawExecutiveSummary(doc: PDFKit.PDFDocument, data: ComplianceData) {
  doc.addPage();
  sectionTitle(doc, "1. Executive Summary");

  const s = data.summary;
  const stats = [
    ["Total Payments", s.total_payments.toLocaleString()],
    ["Total Spend", `$${s.total_spent_usd.toFixed(2)}`],
    ["Active Agents", s.active_agents.toString()],
    ["Unique Endpoints", s.unique_endpoints.toString()],
    ["Avg Payment", `$${s.avg_payment_usd.toFixed(4)}`],
    ["Max Payment", `$${s.max_payment_usd.toFixed(4)}`],
    ["Failed Payments", s.total_failed.toString()],
    ["Blocked Payments", s.total_blocked.toString()],
  ];

  const colW = CONTENT_WIDTH / 2;
  let y = doc.y + 10;
  for (let i = 0; i < stats.length; i += 2) {
    const left = stats[i]!;
    const right = stats[i + 1];

    doc.fontSize(9).fill(MUTED).text(left[0]!, MARGIN, y);
    doc.fontSize(13).fill(TEXT_COLOR).text(left[1]!, MARGIN, y + 14);

    if (right) {
      doc.fontSize(9).fill(MUTED).text(right[0]!, MARGIN + colW, y);
      doc.fontSize(13).fill(TEXT_COLOR).text(right[1]!, MARGIN + colW, y + 14);
    }

    y += 40;
  }
  doc.y = y;
}

function drawAgentInventory(doc: PDFKit.PDFDocument, data: ComplianceData) {
  doc.addPage();
  sectionTitle(doc, "2. Agent Inventory");

  if (data.byAgent.length === 0) {
    doc.fontSize(10).fill(MUTED).text("No agent activity in the selected period.");
    return;
  }

  const cols = [
    { header: "Agent ID", width: 140 },
    { header: "Payments", width: 70 },
    { header: "Total Spend", width: 90 },
    { header: "Avg / Payment", width: 90 },
  ];

  const rows = data.byAgent.map((a) => [
    a.agent_id,
    a.count.toString(),
    `$${a.total_usd.toFixed(2)}`,
    `$${(a.count > 0 ? a.total_usd / a.count : 0).toFixed(4)}`,
  ]);

  drawTable(doc, cols, rows);
}

function drawPaymentActivity(doc: PDFKit.PDFDocument, data: ComplianceData) {
  doc.addPage();
  sectionTitle(doc, "3. Payment Activity");

  if (data.payments.length === 0) {
    doc.fontSize(10).fill(MUTED).text("No payments in the selected period.");
    return;
  }

  const cols = [
    { header: "Date", width: 75 },
    { header: "Agent", width: 80 },
    { header: "Endpoint", width: 100 },
    { header: "Amount", width: 70 },
    { header: "Network", width: 55 },
    { header: "Status", width: 50 },
  ];

  const rows = data.payments.slice(0, 200).map((p) => [
    formatDate(p.timestamp),
    truncate(p.agentExternalId, 12),
    truncate(p.endpoint, 16),
    p.amountUsd != null ? `$${p.amountUsd.toFixed(4)}` : p.amount ?? "—",
    p.network ?? "—",
    p.status,
  ]);

  drawTable(doc, cols, rows);

  if (data.payments.length > 200) {
    doc.moveDown();
    doc.fontSize(9).fill(MUTED).text(
      `Showing 200 of ${data.payments.length} payments. Full data available in the dashboard.`
    );
  }
}

function drawBudgetCompliance(doc: PDFKit.PDFDocument, data: ComplianceData) {
  doc.addPage();
  sectionTitle(doc, "4. Budget Compliance");

  const activePolicies = data.policies.filter((p) => p.isActive);

  const totalPayments = data.summary.total_payments;
  const blocked = data.summary.total_blocked;
  const complianceRate = totalPayments > 0 ? ((totalPayments - blocked) / totalPayments) * 100 : 100;

  doc.fontSize(11).fill(TEXT_COLOR);
  doc.text(`Active Policies: ${activePolicies.length}`);
  doc.text(`Blocked Payments: ${blocked}`);
  doc.text(`Compliance Rate: ${complianceRate.toFixed(1)}%`);
  doc.moveDown();

  if (activePolicies.length > 0) {
    const cols = [
      { header: "Policy Name", width: 180 },
      { header: "Agent", width: 120 },
      { header: "Active", width: 60 },
    ];

    const rows = activePolicies.map((p) => [
      p.name,
      p.agentExternalId ?? "All agents",
      p.isActive ? "Yes" : "No",
    ]);

    drawTable(doc, cols, rows);
  } else {
    doc.fontSize(10).fill(MUTED).text("No budget policies configured.");
  }
}

function drawReceiptLog(doc: PDFKit.PDFDocument, data: ComplianceData) {
  doc.addPage();
  sectionTitle(doc, "5. Receipt Verification Log");

  const total = data.receipts.length;
  const verified = data.receipts.filter((r) => r.verified).length;
  const verifyRate = total > 0 ? ((verified / total) * 100).toFixed(1) : "N/A";

  doc.fontSize(11).fill(TEXT_COLOR);
  doc.text(`Total Receipts: ${total}`);
  doc.text(`Verified: ${verified}`);
  doc.text(`Verification Rate: ${verifyRate}%`);
  doc.moveDown();

  if (data.receipts.length > 0) {
    const cols = [
      { header: "Receipt ID", width: 150 },
      { header: "Payment ID", width: 150 },
      { header: "Verified", width: 60 },
      { header: "Created", width: 90 },
    ];

    const rows = data.receipts.slice(0, 100).map((r) => [
      truncate(r.id, 20),
      truncate(r.paymentId ?? "—", 20),
      r.verified ? "Yes" : "No",
      formatDate(r.createdAt.toISOString()),
    ]);

    drawTable(doc, cols, rows);
  }
}

function drawAlertSummary(doc: PDFKit.PDFDocument, data: ComplianceData) {
  doc.addPage();
  sectionTitle(doc, "6. Alert Summary");

  if (data.alerts.length === 0) {
    doc.fontSize(10).fill(MUTED).text("No alerts triggered in the selected period.");
    return;
  }

  const cols = [
    { header: "Date", width: 80 },
    { header: "Type", width: 80 },
    { header: "Severity", width: 65 },
    { header: "Message", width: 190 },
    { header: "Resolved", width: 55 },
  ];

  const rows = data.alerts.slice(0, 100).map((a) => [
    formatDate(a.createdAt.toISOString()),
    a.type,
    a.severity,
    truncate(a.message, 35),
    a.resolved ? "Yes" : "No",
  ]);

  drawTable(doc, cols, rows);
}

function drawRiskAssessment(doc: PDFKit.PDFDocument, data: ComplianceData) {
  doc.addPage();
  sectionTitle(doc, "7. Risk Assessment");

  const { risk } = data;

  const levelColor = risk.level === "Low" ? "#22c55e" : risk.level === "Medium" ? "#eab308" : "#ef4444";
  doc.fontSize(14).fill(levelColor).text(`Risk Level: ${risk.level}`);
  doc.moveDown();

  doc.fontSize(11).fill(TEXT_COLOR).text("Findings:", { underline: true });
  doc.moveDown(0.5);
  for (const f of risk.findings) {
    doc.fontSize(10).fill(TEXT_COLOR).text(`  •  ${f}`);
  }

  if (risk.recommendations.length > 0) {
    doc.moveDown();
    doc.fontSize(11).fill(TEXT_COLOR).text("Recommendations:", { underline: true });
    doc.moveDown(0.5);
    for (const r of risk.recommendations) {
      doc.fontSize(10).fill(TEXT_COLOR).text(`  •  ${r}`);
    }
  }
}

// --- Helpers ---

function sectionTitle(doc: PDFKit.PDFDocument, title: string) {
  doc.fontSize(16).fill(NAVY).text(title, MARGIN);
  doc.moveTo(MARGIN, doc.y + 4).lineTo(MARGIN + CONTENT_WIDTH, doc.y + 4).strokeColor(NAVY).lineWidth(1).stroke();
  doc.moveDown(0.8);
}

interface Column {
  header: string;
  width: number;
}

function drawTable(doc: PDFKit.PDFDocument, columns: Column[], rows: string[][]) {
  const ROW_HEIGHT = 18;
  let y = doc.y;

  // Header
  doc.rect(MARGIN, y, CONTENT_WIDTH, ROW_HEIGHT).fill(NAVY);
  let x = MARGIN;
  for (const col of columns) {
    doc.fontSize(8).fill(WHITE).text(col.header, x + 4, y + 4, { width: col.width - 8, lineBreak: false });
    x += col.width;
  }
  y += ROW_HEIGHT;

  // Rows
  for (let i = 0; i < rows.length; i++) {
    if (y + ROW_HEIGHT > 742) {
      doc.addPage();
      y = MARGIN;
      // Re-draw header on new page
      doc.rect(MARGIN, y, CONTENT_WIDTH, ROW_HEIGHT).fill(NAVY);
      let hx = MARGIN;
      for (const col of columns) {
        doc.fontSize(8).fill(WHITE).text(col.header, hx + 4, y + 4, { width: col.width - 8, lineBreak: false });
        hx += col.width;
      }
      y += ROW_HEIGHT;
    }

    const bgColor = i % 2 === 0 ? WHITE : LIGHT_ROW;
    doc.rect(MARGIN, y, CONTENT_WIDTH, ROW_HEIGHT).fill(bgColor);

    x = MARGIN;
    const row = rows[i]!;
    for (let j = 0; j < columns.length; j++) {
      doc.fontSize(8).fill(TEXT_COLOR).text(row[j] ?? "", x + 4, y + 4, {
        width: columns[j]!.width - 8,
        lineBreak: false,
      });
      x += columns[j]!.width;
    }
    y += ROW_HEIGHT;
  }

  doc.y = y + 4;
}

function addFooters(doc: PDFKit.PDFDocument) {
  const pageCount = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);
    if (i === 0) continue; // skip cover page
    doc.fontSize(7).fill(MUTED).text(
      `Generated by Sentinel  |  sentinel.valeocash.com  |  Page ${i} of ${pageCount - 1}`,
      MARGIN,
      760,
      { width: CONTENT_WIDTH, align: "center" }
    );
  }
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function formatDateTime(iso: string): string {
  const d = new Date(iso);
  return `${formatDate(iso)} ${d.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "UTC" })} UTC`;
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max - 3) + "..." : s;
}
