import PptxGenJS from "pptxgenjs";
import type { ComplianceData } from "./types";

const BG = "1a1a2e";
const WHITE = "FFFFFF";
const CYAN = "00d4ff";
const MUTED = "8899aa";
const CARD_BG = "262640";
const GREEN = "22c55e";
const YELLOW = "eab308";
const RED = "ef4444";

function addBgSlide(pptx: PptxGenJS): PptxGenJS.Slide {
  const slide = pptx.addSlide();
  slide.background = { color: BG };
  return slide;
}

export async function generateCompliancePPTX(data: ComplianceData): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.author = "Sentinel";
  pptx.company = "Sentinel – x402 Payment Intelligence";
  pptx.title = `Compliance Report – ${data.teamName}`;
  pptx.layout = "LAYOUT_WIDE";

  slideTitlePage(pptx, data);
  slideExecutiveSummary(pptx, data);
  slidePaymentTrend(pptx, data);
  slideAgentOverview(pptx, data);
  slideTopEndpoints(pptx, data);
  slideNetworkDistribution(pptx, data);
  slideBudgetCompliance(pptx, data);
  slideAlertsIncidents(pptx, data);
  slideRiskAssessment(pptx, data);
  slideReceipts(pptx, data);
  slideRecommendations(pptx, data);
  slideNextSteps(pptx, data);

  const output = await pptx.write({ outputType: "nodebuffer" });
  return output as Buffer;
}

function addSlideTitle(slide: PptxGenJS.Slide, title: string) {
  slide.addText(title, {
    x: 0.5,
    y: 0.3,
    w: 9,
    h: 0.5,
    fontSize: 22,
    color: WHITE,
    fontFace: "Helvetica",
    bold: true,
  });
  slide.addShape("rect" as unknown as PptxGenJS.ShapeType, {
    x: 0.5,
    y: 0.85,
    w: 2,
    h: 0.04,
    fill: { color: CYAN },
  });
}

function addFooter(slide: PptxGenJS.Slide) {
  slide.addText("Generated by Sentinel  |  sentinel.valeocash.com", {
    x: 0.5,
    y: 7.0,
    w: 9,
    h: 0.3,
    fontSize: 8,
    color: MUTED,
    fontFace: "Helvetica",
  });
}

// Slide 1
function slideTitlePage(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);

  slide.addText("x402 Payment\nCompliance Report", {
    x: 0.8,
    y: 1.5,
    w: 8,
    h: 2,
    fontSize: 36,
    color: WHITE,
    fontFace: "Helvetica",
    bold: true,
    lineSpacing: 42,
  });

  slide.addText(data.teamName, {
    x: 0.8,
    y: 3.8,
    w: 8,
    h: 0.5,
    fontSize: 18,
    color: CYAN,
    fontFace: "Helvetica",
  });

  slide.addText(
    `${fmtDate(data.startDate)} — ${fmtDate(data.endDate)}`,
    { x: 0.8, y: 4.4, w: 8, h: 0.4, fontSize: 14, color: MUTED, fontFace: "Helvetica" }
  );

  slide.addText(
    `Generated: ${new Date(data.generatedAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    { x: 0.8, y: 4.9, w: 8, h: 0.4, fontSize: 11, color: MUTED, fontFace: "Helvetica" }
  );

  addFooter(slide);
}

// Slide 2
function slideExecutiveSummary(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Executive Summary");

  const s = data.summary;
  const cards = [
    { label: "Total Payments", value: s.total_payments.toLocaleString() },
    { label: "Total Spend", value: `$${s.total_spent_usd.toFixed(2)}` },
    { label: "Active Agents", value: s.active_agents.toString() },
    { label: "Unique Endpoints", value: s.unique_endpoints.toString() },
  ];

  cards.forEach((c, i) => {
    const x = 0.5 + i * 2.4;
    slide.addShape("roundRect" as unknown as PptxGenJS.ShapeType, {
      x,
      y: 1.4,
      w: 2.1,
      h: 1.4,
      fill: { color: CARD_BG },
      rectRadius: 0.1,
    });
    slide.addText(c.value, {
      x,
      y: 1.6,
      w: 2.1,
      h: 0.7,
      fontSize: 24,
      color: CYAN,
      fontFace: "Helvetica",
      bold: true,
      align: "center",
    });
    slide.addText(c.label, {
      x,
      y: 2.3,
      w: 2.1,
      h: 0.4,
      fontSize: 10,
      color: MUTED,
      fontFace: "Helvetica",
      align: "center",
    });
  });

  const moreStats = [
    `Average Payment: $${s.avg_payment_usd.toFixed(4)}`,
    `Maximum Payment: $${s.max_payment_usd.toFixed(4)}`,
    `Failed: ${s.total_failed}  |  Blocked: ${s.total_blocked}`,
  ];

  slide.addText(moreStats.join("\n"), {
    x: 0.5,
    y: 3.3,
    w: 9,
    h: 1.2,
    fontSize: 11,
    color: WHITE,
    fontFace: "Helvetica",
    lineSpacing: 20,
  });

  addFooter(slide);
}

// Slide 3
function slidePaymentTrend(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Payment Trend");

  if (data.timeseries.length === 0) {
    slide.addText("No payment data available for the selected period.", {
      x: 0.5, y: 2.5, w: 9, h: 1, fontSize: 14, color: MUTED, fontFace: "Helvetica",
    });
    addFooter(slide);
    return;
  }

  const headerOpts: PptxGenJS.TableCellProps = {
    fill: { color: CARD_BG },
    color: CYAN,
    fontSize: 9,
    fontFace: "Helvetica",
    bold: true,
    border: { type: "solid", color: "333355", pt: 0.5 },
    valign: "middle",
  };
  const cellOpts: PptxGenJS.TableCellProps = {
    color: WHITE,
    fontSize: 9,
    fontFace: "Helvetica",
    border: { type: "solid", color: "333355", pt: 0.5 },
    valign: "middle",
  };

  const tableRows: PptxGenJS.TableRow[] = [
    [
      { text: "Date", options: headerOpts },
      { text: "Payments", options: headerOpts },
      { text: "Spend (USD)", options: headerOpts },
    ],
  ];

  const entries = data.timeseries.slice(0, 20);
  for (const t of entries) {
    tableRows.push([
      { text: fmtDate(t.timestamp), options: cellOpts },
      { text: t.count.toString(), options: cellOpts },
      { text: `$${t.total_usd.toFixed(2)}`, options: cellOpts },
    ]);
  }

  slide.addTable(tableRows, { x: 0.5, y: 1.2, w: 6, colW: [2, 2, 2] });
  addFooter(slide);
}

// Slide 4
function slideAgentOverview(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Agent Overview");

  const hOpts: PptxGenJS.TableCellProps = {
    fill: { color: CARD_BG }, color: CYAN, fontSize: 9, fontFace: "Helvetica", bold: true,
    border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
  };
  const cOpts: PptxGenJS.TableCellProps = {
    color: WHITE, fontSize: 9, fontFace: "Helvetica",
    border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
  };

  const rows: PptxGenJS.TableRow[] = [
    [
      { text: "Agent ID", options: hOpts },
      { text: "Payments", options: hOpts },
      { text: "Total Spend", options: hOpts },
      { text: "Avg / Payment", options: hOpts },
    ],
  ];

  for (const a of data.byAgent.slice(0, 15)) {
    rows.push([
      { text: a.agent_id, options: cOpts },
      { text: a.count.toString(), options: cOpts },
      { text: `$${a.total_usd.toFixed(2)}`, options: cOpts },
      { text: `$${(a.count > 0 ? a.total_usd / a.count : 0).toFixed(4)}`, options: cOpts },
    ]);
  }

  slide.addTable(rows, { x: 0.5, y: 1.2, w: 9, colW: [3, 2, 2, 2] });
  addFooter(slide);
}

// Slide 5
function slideTopEndpoints(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Top Endpoints");

  const hOpts: PptxGenJS.TableCellProps = {
    fill: { color: CARD_BG }, color: CYAN, fontSize: 9, fontFace: "Helvetica", bold: true,
    border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
  };
  const cOpts: PptxGenJS.TableCellProps = {
    color: WHITE, fontSize: 9, fontFace: "Helvetica",
    border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
  };

  const rows: PptxGenJS.TableRow[] = [
    [
      { text: "Endpoint", options: hOpts },
      { text: "Payments", options: hOpts },
      { text: "Total Spend", options: hOpts },
    ],
  ];

  for (const e of data.byEndpoint.slice(0, 15)) {
    rows.push([
      { text: e.endpoint_domain, options: cOpts },
      { text: e.count.toString(), options: cOpts },
      { text: `$${e.total_usd.toFixed(2)}`, options: cOpts },
    ]);
  }

  slide.addTable(rows, { x: 0.5, y: 1.2, w: 9, colW: [4.5, 2.25, 2.25] });
  addFooter(slide);
}

// Slide 6
function slideNetworkDistribution(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Network Distribution");

  const totalSpend = data.summary.total_spent_usd || 1;

  const hOpts: PptxGenJS.TableCellProps = {
    fill: { color: CARD_BG }, color: CYAN, fontSize: 9, fontFace: "Helvetica", bold: true,
    border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
  };
  const cOpts: PptxGenJS.TableCellProps = {
    color: WHITE, fontSize: 9, fontFace: "Helvetica",
    border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
  };

  const rows: PptxGenJS.TableRow[] = [
    [
      { text: "Network", options: hOpts },
      { text: "Payments", options: hOpts },
      { text: "Total Spend", options: hOpts },
      { text: "% of Total", options: hOpts },
    ],
  ];

  for (const n of data.byNetwork) {
    const pct = ((n.total_usd / totalSpend) * 100).toFixed(1);
    rows.push([
      { text: n.network ?? "Unknown", options: cOpts },
      { text: n.count.toString(), options: cOpts },
      { text: `$${n.total_usd.toFixed(2)}`, options: cOpts },
      { text: `${pct}%`, options: cOpts },
    ]);
  }

  slide.addTable(rows, { x: 0.5, y: 1.2, w: 9, colW: [3, 2, 2, 2] });
  addFooter(slide);
}

// Slide 7
function slideBudgetCompliance(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Budget Compliance");

  const activePolicies = data.policies.filter((p) => p.isActive);
  const total = data.summary.total_payments;
  const blocked = data.summary.total_blocked;
  const rate = total > 0 ? ((total - blocked) / total) * 100 : 100;

  const rateColor = rate >= 99 ? GREEN : rate >= 95 ? YELLOW : RED;

  slide.addText(`${rate.toFixed(1)}%`, {
    x: 0.5, y: 1.3, w: 3, h: 1, fontSize: 48, color: rateColor,
    fontFace: "Helvetica", bold: true,
  });
  slide.addText("Compliance Rate", {
    x: 0.5, y: 2.3, w: 3, h: 0.4, fontSize: 12, color: MUTED, fontFace: "Helvetica",
  });

  slide.addText(
    `Active Policies: ${activePolicies.length}\nBlocked Payments: ${blocked}\nTotal Payments: ${total}`,
    { x: 4, y: 1.3, w: 5, h: 1.5, fontSize: 12, color: WHITE, fontFace: "Helvetica", lineSpacing: 22 }
  );

  if (activePolicies.length > 0) {
    const hOpts: PptxGenJS.TableCellProps = {
      fill: { color: CARD_BG }, color: CYAN, fontSize: 9, fontFace: "Helvetica", bold: true,
      border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
    };
    const cOpts: PptxGenJS.TableCellProps = {
      color: WHITE, fontSize: 9, fontFace: "Helvetica",
      border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
    };

    const rows: PptxGenJS.TableRow[] = [
      [
        { text: "Policy", options: hOpts },
        { text: "Agent", options: hOpts },
      ],
    ];

    for (const p of activePolicies.slice(0, 10)) {
      rows.push([
        { text: p.name, options: cOpts },
        { text: p.agentExternalId ?? "All agents", options: cOpts },
      ]);
    }

    slide.addTable(rows, { x: 0.5, y: 3.5, w: 8, colW: [4, 4] });
  }

  addFooter(slide);
}

// Slide 8
function slideAlertsIncidents(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Alerts & Incidents");

  if (data.alerts.length === 0) {
    slide.addText("No alerts triggered in this period.", {
      x: 0.5, y: 2.5, w: 9, h: 1, fontSize: 14, color: MUTED, fontFace: "Helvetica",
    });
    addFooter(slide);
    return;
  }

  const critical = data.alerts.filter((a) => a.severity === "critical").length;
  const high = data.alerts.filter((a) => a.severity === "high").length;
  const medium = data.alerts.filter((a) => a.severity === "medium").length;
  const low = data.alerts.filter((a) => a.severity === "low").length;
  const resolved = data.alerts.filter((a) => a.resolved).length;

  slide.addText(
    `Total: ${data.alerts.length}  |  Critical: ${critical}  |  High: ${high}  |  Medium: ${medium}  |  Low: ${low}\nResolved: ${resolved} / ${data.alerts.length}`,
    { x: 0.5, y: 1.2, w: 9, h: 0.8, fontSize: 11, color: WHITE, fontFace: "Helvetica", lineSpacing: 20 }
  );

  const hOpts: PptxGenJS.TableCellProps = {
    fill: { color: CARD_BG }, color: CYAN, fontSize: 9, fontFace: "Helvetica", bold: true,
    border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
  };
  const cOpts: PptxGenJS.TableCellProps = {
    color: WHITE, fontSize: 9, fontFace: "Helvetica",
    border: { type: "solid", color: "333355", pt: 0.5 }, valign: "middle",
  };

  const rows: PptxGenJS.TableRow[] = [
    [
      { text: "Date", options: hOpts },
      { text: "Severity", options: hOpts },
      { text: "Type", options: hOpts },
      { text: "Message", options: hOpts },
    ],
  ];

  for (const a of data.alerts.slice(0, 12)) {
    rows.push([
      { text: fmtDate(a.createdAt.toISOString()), options: cOpts },
      { text: a.severity, options: cOpts },
      { text: a.type, options: cOpts },
      { text: a.message.length > 50 ? a.message.slice(0, 47) + "..." : a.message, options: cOpts },
    ]);
  }

  slide.addTable(rows, { x: 0.5, y: 2.3, w: 9, colW: [2, 1.5, 2, 3.5] });
  addFooter(slide);
}

// Slide 9
function slideRiskAssessment(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Risk Assessment");

  const { risk } = data;
  const levelColor = risk.level === "Low" ? GREEN : risk.level === "Medium" ? YELLOW : RED;

  slide.addText(risk.level, {
    x: 0.5, y: 1.3, w: 3, h: 0.8, fontSize: 36, color: levelColor,
    fontFace: "Helvetica", bold: true,
  });
  slide.addText("Overall Risk Level", {
    x: 0.5, y: 2.1, w: 3, h: 0.4, fontSize: 11, color: MUTED, fontFace: "Helvetica",
  });

  const findingsText = risk.findings.map((f) => `•  ${f}`).join("\n");
  slide.addText("Findings", {
    x: 0.5, y: 2.8, w: 9, h: 0.4, fontSize: 13, color: WHITE,
    fontFace: "Helvetica", bold: true,
  });
  slide.addText(findingsText, {
    x: 0.7, y: 3.2, w: 8.5, h: 3, fontSize: 10, color: WHITE,
    fontFace: "Helvetica", lineSpacing: 18,
  });

  addFooter(slide);
}

// Slide 10
function slideReceipts(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Cryptographic Receipts");

  const total = data.receipts.length;
  const verified = data.receipts.filter((r) => r.verified).length;
  const rate = total > 0 ? ((verified / total) * 100).toFixed(1) : "N/A";

  const cards = [
    { label: "Total Receipts", value: total.toString() },
    { label: "Verified", value: verified.toString() },
    { label: "Verification Rate", value: `${rate}%` },
  ];

  cards.forEach((c, i) => {
    const x = 0.5 + i * 3;
    slide.addShape("roundRect" as unknown as PptxGenJS.ShapeType, {
      x, y: 1.4, w: 2.7, h: 1.4, fill: { color: CARD_BG }, rectRadius: 0.1,
    });
    slide.addText(c.value, {
      x, y: 1.6, w: 2.7, h: 0.7, fontSize: 28, color: CYAN,
      fontFace: "Helvetica", bold: true, align: "center",
    });
    slide.addText(c.label, {
      x, y: 2.3, w: 2.7, h: 0.4, fontSize: 10, color: MUTED,
      fontFace: "Helvetica", align: "center",
    });
  });

  addFooter(slide);
}

// Slide 11
function slideRecommendations(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Recommendations");

  const { recommendations } = data.risk;

  if (recommendations.length === 0) {
    slide.addText("No recommendations — your setup looks great!", {
      x: 0.5, y: 2.5, w: 9, h: 1, fontSize: 14, color: GREEN, fontFace: "Helvetica",
    });
    addFooter(slide);
    return;
  }

  recommendations.forEach((r, i) => {
    slide.addShape("roundRect" as unknown as PptxGenJS.ShapeType, {
      x: 0.5, y: 1.3 + i * 0.7, w: 9, h: 0.55, fill: { color: CARD_BG }, rectRadius: 0.05,
    });
    slide.addText(`${i + 1}.  ${r}`, {
      x: 0.7, y: 1.35 + i * 0.7, w: 8.5, h: 0.5, fontSize: 11, color: WHITE,
      fontFace: "Helvetica",
    });
  });

  addFooter(slide);
}

// Slide 12
function slideNextSteps(pptx: PptxGenJS, data: ComplianceData) {
  const slide = addBgSlide(pptx);
  addSlideTitle(slide, "Next Steps");

  const steps = [
    "Review findings and resolve open alerts",
    "Configure budget policies for uncovered agents",
    "Set up scheduled compliance reports (weekly/monthly)",
    "Share this deck with your compliance team",
  ];

  steps.forEach((s, i) => {
    slide.addText(`${i + 1}.`, {
      x: 0.5, y: 1.5 + i * 0.6, w: 0.5, h: 0.5, fontSize: 14, color: CYAN,
      fontFace: "Helvetica", bold: true,
    });
    slide.addText(s, {
      x: 1.1, y: 1.5 + i * 0.6, w: 8, h: 0.5, fontSize: 13, color: WHITE,
      fontFace: "Helvetica",
    });
  });

  slide.addText("Dashboard: sentinel.valeocash.com/dashboard", {
    x: 0.5, y: 4.5, w: 9, h: 0.5, fontSize: 12, color: CYAN, fontFace: "Helvetica",
  });

  slide.addText("Compliance page: sentinel.valeocash.com/dashboard/compliance", {
    x: 0.5, y: 5.0, w: 9, h: 0.5, fontSize: 12, color: MUTED, fontFace: "Helvetica",
  });

  addFooter(slide);
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}
