import type { PageTree } from "fumadocs-core/server";

export const pageTree: PageTree.Root = {
  name: "Sentinel",
  children: [
    { type: "page", name: "Introduction", url: "/docs" },
    { type: "separator", name: "Getting Started" },
    { type: "page", name: "Quick Start", url: "/docs/quickstart" },
    { type: "page", name: "How It Works", url: "/docs/how-it-works" },
    { type: "separator", name: "SDK Reference" },
    { type: "page", name: "wrapWithSentinel", url: "/docs/sdk/wrap-with-sentinel" },
    { type: "page", name: "Budget Policies", url: "/docs/sdk/budget-policies" },
    { type: "page", name: "Audit Logger", url: "/docs/sdk/audit-ledger" },
    { type: "page", name: "Storage Backends", url: "/docs/sdk/storage-backends" },
    { type: "page", name: "Error Handling", url: "/docs/sdk/error-handling" },
    { type: "page", name: "Types Reference", url: "/docs/sdk/types" },
    { type: "separator", name: "Guides" },
    { type: "page", name: "Single Agent", url: "/docs/guides/single-agent" },
    { type: "page", name: "Multi-Agent Fleet", url: "/docs/guides/multi-agent-fleet" },
    { type: "page", name: "Enterprise Setup", url: "/docs/guides/enterprise" },
    { type: "page", name: "Proxy Mode", url: "/docs/guides/proxy" },
    { type: "page", name: "Migration Guide", url: "/docs/guides/migration" },
    { type: "separator", name: "Dashboard" },
    { type: "page", name: "Dashboard Overview", url: "/docs/dashboard/overview" },
    { type: "page", name: "Payments", url: "/docs/dashboard/payments" },
    { type: "page", name: "Agents", url: "/docs/dashboard/agents" },
    { type: "page", name: "Policies", url: "/docs/dashboard/policies" },
    { type: "separator", name: "API Reference" },
    { type: "page", name: "Authentication", url: "/docs/api/authentication" },
    { type: "page", name: "Events Ingest", url: "/docs/api/events" },
    { type: "page", name: "Payments API", url: "/docs/api/payments" },
    { type: "page", name: "Analytics API", url: "/docs/api/analytics" },
    { type: "page", name: "Management API", url: "/docs/api/management" },
    { type: "separator", name: "Resources" },
    { type: "page", name: "Explorer", url: "/explorer" },
  ],
};
